# This file contains configuration options for GolangCI-Lint.
#
# - It requires golangci-lint 1.48.0 or newer.
# - Available linters see: https://golangci-lint.run/usage/linters/
# - Sample of config see: https://golangci-lint.run/usage/configuration/#config-file

# Options for analysis running
run:
  # Include test files.
  tests: true
  # List of build tags, all linters use it. Default is empty list.
  build-tags:
    - golangci
  # Allow multiple parallel golangci-lint instances running.
  allow-parallel-runners: true

issues:
  # Which dirs to skip. Issues from them won't be reported.
  exclude-dirs:
    - .github

# Output configuration options
output:
  # Sorts results by: filepath, line and column
  sort-results: true

# Enabled all linters. Conf settings may follow.
linters:
  enable-all: true
  disable:
  # Remove deactivated deprecated linters
  #- exhaustivestruct
  #- golint
  #- ifshort
  #- interfacer
  #- maligned
  #- scopelint
  #- structcheck
  #- varcheck
  #- deadcode
  #- nosnakecase
  #
  # Disable deprecated and avandonded linters
  - execinquery
  - exportloopref
  - gomnd
linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          # Go standard library
          - $gostd
          # Required for testing
          - github.com/KEINOS/go-argonize
          - github.com/stretchr/testify
          # Deprecated but still used for simple error handling
          - github.com/pkg/errors
