# -----------------------------------------------------------------------------
#  Build Stage (Go)
# -----------------------------------------------------------------------------
FROM golang:alpine AS build

RUN apk add --no-cache \
    git \
    alpine-sdk \
    build-base

COPY . /workspaces

WORKDIR /workspaces/_tests

RUN \
        go mod init sample && \
        # Ensure the sample module uses the local copy of github.com/KEINOS/go-argonize
        echo "replace github.com/KEINOS/go-argonize => ../" >> go.mod && \
        go mod tidy && \
        go install \
            -ldflags="-s -w -extldflags \"-static\"" \
            .

# -----------------------------------------------------------------------------
#  Main Stage (PHP)
# -----------------------------------------------------------------------------
FROM php:alpine

WORKDIR /workspaces

COPY --from=build /go/bin/sample /usr/local/bin/sample

ENTRYPOINT php /workspaces/main.php
