# -----------------------------------------------------------------------------
#  Build Stage (Go)
# -----------------------------------------------------------------------------
FROM golang:alpine AS build

RUN apk add --no-cache \
    git \
    alpine-sdk \
    build-base

COPY . /workspaces

WORKDIR /workspaces/_examples

RUN \
    go mod init sample && \
    go mod tidy && \
    go install \
      -ldflags="-s -w -extldflags \"-static\"" \
      .

# -----------------------------------------------------------------------------
#  Main Stage (PHP)
# -----------------------------------------------------------------------------
FROM php:alpine

WORKDIR /workspaces

COPY --from=build /go/bin/sample /usr/local/bin/sample

ENTRYPOINT php /workspaces/main.php
